name: ZAP backend production nightly analysis

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  URL_TO_SCAN: "https://pablomuar-calculator-backend.azurewebsites.net"

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run ZAP DAST Scan
      run: |
        docker run -t --rm \
          softwaresecurityproject/zap-stable zap-baseline.py \
          -t $URL_TO_SCAN \
          -r zap_report.html

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: backend-zap-report
        path: zap_report.html
